#!/usr/bin/env python3
"""Reproducible export/check for the two committed docs that must always
match generated/source-of-truth content (see
docs/OPENFOODTOX_DELIVERY_CONSISTENCY_TASK.md):

- ``docs/OPENFOODTOX_PILOT_REVIEW_DRAFTS.md`` -- the four pilot
  identities' EN/BG draft bodies, verbatim from a pilot run's
  ``<id>_profile.json`` (``draft_en``/``draft_bg``/``internal_evidence_en``).
  "Eight bodies" = 4 identities x (EN + BG).
- ``docs/OPENFOODTOX_CLAIM_SOURCE_MATRIX.md`` -- every editorial claim,
  generated directly from ``editorial_content.py``, never hand-transcribed.

``export`` writes the committed doc from the live source of truth.
``check`` re-derives the same content in memory and diffs it against what
is currently committed, failing loudly (non-zero exit, printed diff) on any
mismatch -- including whitespace/line-ending differences, since those are
exactly the kind of silent drift this tool exists to catch. There is no
"allowed" hand-written prose inside either committed file: every line is
produced by this script, so a `check` failure always means `export` was not
re-run after a change, never a definitional disagreement about what counts.

Usage::

    python -m scripts.openfoodtox.export_docs review-drafts \\
        --output-dir /path/to/pilot/vN [--check]
    python -m scripts.openfoodtox.export_docs claim-matrix [--check]
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts.openfoodtox.editorial_content import EDITORIAL_CONTENT  # noqa: E402
from scripts.openfoodtox.evidence_bundle import _display_name  # noqa: E402
from scripts.openfoodtox.catalogue_snapshot import CatalogueIdentity  # noqa: E402

_BACKEND_ROOT = Path(__file__).resolve().parents[2]  # .../nutriguard-backend
_REVIEW_DRAFTS_PATH = _BACKEND_ROOT / "docs" / "OPENFOODTOX_PILOT_REVIEW_DRAFTS.md"
_CLAIM_MATRIX_PATH = _BACKEND_ROOT / "docs" / "OPENFOODTOX_CLAIM_SOURCE_MATRIX.md"

# Profile JSON filename -> catalogue id, used only to find the right file
# in a pilot output directory (matches pilot.py's own naming).
_PROFILE_FILES = {
    "E250": "e250_sodium_nitrite_profile.json",
    "E150d": "adhoc_query_E150d_profile.json",
    "E330": "e330_citric_acid_profile.json",
    "E951": "e951_aspartame_profile.json",
}


def _fence(text: str) -> str:
    return "```text\n" + text.rstrip("\n") + "\n```"


def _render_review_drafts(output_dir: str) -> str:
    lines: list[str] = []
    lines.append("# OpenFoodTox pilot -- complete EN/BG review drafts (for Codex review)")
    lines.append("")
    lines.append(
        "Mechanically generated by `python -m scripts.openfoodtox.export_docs "
        "review-drafts --output-dir <dir>` -- every body below is a verbatim, "
        "fenced-code-block export of the named pilot output's own "
        "`draft_en`/`draft_bg`/`internal_evidence_en` JSON fields. **Never "
        "hand-edit the content inside a fenced block below** -- re-run the "
        "export command after any code/content change instead; "
        "`... export_docs review-drafts --output-dir <dir> --check` fails "
        "loudly if this file and the named output directory's JSON ever "
        "disagree (including whitespace), so drift cannot go unnoticed."
    )
    lines.append("")
    lines.append(f"Generated from: `{output_dir}` (see that directory's own `pilot_summary.json` for exact producing-code provenance -- git SHA, dirty-tree status, and the staging catalogue used -- not duplicated here to avoid a second, driftable copy of that information).")
    lines.append("")
    lines.append("---")
    lines.append("")

    for e_number, filename in _PROFILE_FILES.items():
        path = os.path.join(output_dir, filename)
        with open(path, encoding="utf-8") as f:
            profile = json.load(f)
        cat = CatalogueIdentity(
            id="x",
            common_name=profile["catalogue_identity"]["common_name"],
            e_number_raw=profile["catalogue_identity"]["e_number_raw"],
            e_number_normalized=profile["catalogue_identity"]["e_number_normalized"],
            cas_number_raw=None,
            cas_number_normalized=None,
            source=profile["catalogue_identity"]["source"],
        )
        name_en, name_bg = _display_name(cat)
        eligible_count = sum(
            1 for rv in profile["deduplicated_reference_values"]
            if not rv.get("feed_or_livestock_context") and rv["review_eligibility"]["consumer_guidance_eligible"]
        )
        total_consumer_count = sum(1 for rv in profile["deduplicated_reference_values"] if not rv.get("feed_or_livestock_context"))
        excluded_feed = profile.get("consumer_draft_excluded_feed_or_worker_value_count", 0)

        lines.append(f"## {e_number} -- {name_en} / {name_bg}")
        lines.append("")
        lines.append(f"- `outcome`: `{profile['outcome']}`")
        lines.append(
            f"- Numeric gating: {eligible_count} of {total_consumer_count} consumer-facing reference value(s) "
            f"`consumer_guidance_eligible`"
            + (f"; {excluded_feed} feed/worker value(s) excluded from this preview entirely (operator bundle only)" if excluded_feed else "")
            + "."
        )
        if profile.get("editorial_operator_only_notes"):
            lines.append(
                f"- {len(profile['editorial_operator_only_notes'])} operator-only editorial note(s) exist for this "
                "identity (externally-sourced figures withheld from this preview under the same gating policy) -- "
                "never shown below; see `editorial_operator_only_notes` in the profile JSON."
            )
        lines.append("")
        lines.append("### EN draft")
        lines.append("")
        lines.append(_fence(profile["draft_en"]))
        lines.append("")
        lines.append("### BG draft")
        lines.append("")
        lines.append(_fence(profile["draft_bg"]))
        lines.append("")
        lines.append("### Internal evidence (verbatim, not for publication)")
        lines.append("")
        lines.append(_fence(profile["internal_evidence_en"]))
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append(
        "No section above authorizes scientific/translation review promotion or "
        "publication -- every profile's `statuses.scientific_review` and "
        "`statuses.translation_review` remain `not_reviewed`."
    )
    lines.append("")
    return "\n".join(lines)


def _render_claim_matrix() -> str:
    rows: list[dict] = []
    cid = 0
    for e_number, entry in EDITORIAL_CONTENT.items():

        def add(field_name: str, st, review: str = "not_reviewed") -> None:
            nonlocal cid
            cid += 1
            rows.append(
                {
                    "id": f"{e_number}-{cid:02d}",
                    "e_number": e_number,
                    "field": field_name,
                    "en": st.en,
                    "source_kind": st.source_kind,
                    "source": st.source,
                    "review_status": review,
                }
            )

        if entry.identity:
            add("identity", entry.identity)
        if entry.purpose:
            add("purpose", entry.purpose)
        for note in entry.effects:
            add(f"effects:{note.evidence_type}", note.text)
        for exc in entry.population_exceptions:
            add("population_exception", exc)
        if entry.group_scope_note:
            add("group_scope_note", entry.group_scope_note)
        for note in entry.operator_only_notes:
            add("operator_only_note", note, review="internal_only_never_shown_to_consumer")
        if entry.editorial_chemical_basis:
            eb = entry.editorial_chemical_basis
            cid += 1
            rows.append(
                {
                    "id": f"{e_number}-{cid:02d}",
                    "e_number": e_number,
                    "field": "editorial_chemical_basis",
                    "en": eb["basis_en"],
                    "source_kind": "external_primary_source",
                    "source": eb["source"],
                    "review_status": "not_reviewed",
                }
            )

    lines: list[str] = []
    lines.append("# OpenFoodTox pilot -- editorial claim/source matrix")
    lines.append("")
    lines.append(
        "Mechanically generated by `python -m scripts.openfoodtox.export_docs "
        "claim-matrix` directly from `scripts/openfoodtox/editorial_content.py` "
        "-- never hand-transcribed. `... export_docs claim-matrix --check` "
        "fails loudly if this file and that module ever disagree. Per "
        "`docs/OPENFOODTOX_DELIVERY_CONSISTENCY_TASK.md` item 2, full source "
        "text (not truncated) is kept here so a reviewer can follow every "
        "citation without opening the module; the EN claim text is still "
        "shown abbreviated (full text next to the field name indicated, in "
        "`editorial_content.py`) since reproducing every claim's whole "
        "paragraph here would duplicate, not aid, review."
    )
    lines.append("")
    lines.append(
        "**Source kinds**: `openfoodtox_dossier` (an OpenFoodTox-extracted "
        "quote/field), `tracked_seed_csv`/`tracked_seed_json` (NutriGuard's "
        "own already-curated, git-tracked seed data -- a content *origin*, "
        "never independent scientific evidence on its own), "
        "`external_primary_source` (a primary document read directly in this "
        "session, with its own citation). **`review_status`**: `not_reviewed` "
        "for every row -- source tracing by an agent is not independent "
        "scientific or translation approval; `internal_only_never_shown_to_consumer` "
        "rows never appear in `draft_en`/`draft_bg` at all."
    )
    lines.append("")
    lines.append("| ID | Field | EN claim (abbreviated) | Source kind | Source (full citation) | Review status |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for r in rows:
        en = " ".join(r["en"].split())
        en = en if len(en) <= 90 else en[:89] + "…"
        src = " ".join(r["source"].split())
        # Full citation, not truncated (item 2's explicit requirement) --
        # escape pipes so a long citation can't break the table.
        src = src.replace("|", "\\|")
        lines.append(f"| {r['id']} | {r['field']} | {en} | {r['source_kind']} | {src} | {r['review_status']} |")
    lines.append("")
    return "\n".join(lines)


def _export_or_check(content: str, path: Path, check: bool) -> bool:
    if check:
        if not path.exists():
            print(f"CHECK FAILED: {path} does not exist.")
            return False
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            print(f"CHECK OK: {path} matches generated content exactly.")
            return True
        print(f"CHECK FAILED: {path} does not match generated content.")
        existing_lines = existing.splitlines()
        new_lines = content.splitlines()
        shown = 0
        for i, (a, b) in enumerate(zip(existing_lines, new_lines)):
            if a != b:
                print(f"  line {i + 1} differs:\n    committed: {a!r}\n    generated: {b!r}")
                shown += 1
                if shown >= 10:
                    print("  ... (further diffs truncated)")
                    break
        if len(existing_lines) != len(new_lines):
            print(f"  line count differs: committed={len(existing_lines)} generated={len(new_lines)}")
        return False
    path.write_text(content, encoding="utf-8")
    print(f"EXPORTED: {path}")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    rd = sub.add_parser("review-drafts")
    rd.add_argument("--output-dir", required=True, help="A pilot output directory containing the four *_profile.json files")
    rd.add_argument("--check", action="store_true")

    cm = sub.add_parser("claim-matrix")
    cm.add_argument("--check", action="store_true")

    args = parser.parse_args(argv)

    if args.command == "review-drafts":
        content = _render_review_drafts(args.output_dir)
        ok = _export_or_check(content, _REVIEW_DRAFTS_PATH, args.check)
    else:
        content = _render_claim_matrix()
        ok = _export_or_check(content, _CLAIM_MATRIX_PATH, args.check)

    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
