"""initial schema

Revision ID: 64dfe47cbbf7
Revises: 
Create Date: 2026-08-12 05:17:32.517991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64dfe47cbbf7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('e_number', sa.String(length=16), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('purpose_in_food', sa.Text(), nullable=False),
    sa.Column('health_concerns', sa.Text(), nullable=False),
    sa.Column('evidence_level', sa.String(length=255), nullable=False),
    sa.Column('countries_restricted_or_banned', sa.Text(), nullable=False),
    sa.Column('efsa_status', sa.String(length=255), nullable=False),
    sa.Column('fda_status', sa.String(length=255), nullable=False),
    sa.Column('who_iarc_classification', sa.String(length=255), nullable=True),
    sa.Column('acceptable_daily_intake', sa.String(length=128), nullable=False),
    sa.Column('side_effects', sa.Text(), nullable=False),
    sa.Column('allergens', sa.Text(), nullable=False),
    sa.Column('references', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.Enum('SAFE', 'MODERATE', 'POTENTIAL_CONCERN', 'HIGH_CONCERN', name='risk_level'), nullable=False),
    sa.Column('is_gluten', sa.Boolean(), nullable=False),
    sa.Column('is_lactose', sa.Boolean(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('is_halal', sa.Boolean(), nullable=False),
    sa.Column('is_kosher', sa.Boolean(), nullable=False),
    sa.Column('bad_for_diabetes', sa.Boolean(), nullable=False),
    sa.Column('bad_for_hypertension', sa.Boolean(), nullable=False),
    sa.Column('bad_for_kidney_disease', sa.Boolean(), nullable=False),
    sa.Column('bad_for_gout', sa.Boolean(), nullable=False),
    sa.Column('bad_for_pregnancy', sa.Boolean(), nullable=False),
    sa.Column('bad_for_children', sa.Boolean(), nullable=False),
    sa.Column('bad_for_high_cholesterol', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_common_name'), 'ingredients', ['common_name'], unique=False)
    op.create_index(op.f('ix_ingredients_e_number'), 'ingredients', ['e_number'], unique=True)
    op.create_table('products',
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('raw_ingredient_text', sa.Text(), nullable=False),
    sa.Column('ingredient_ids', sa.Text(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('nova_group', sa.Integer(), nullable=False),
    sa.Column('sugar_grams', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('sodium_mg', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('saturated_fat_grams', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('has_artificial_sweeteners', sa.Boolean(), nullable=False),
    sa.Column('has_preservatives', sa.Boolean(), nullable=False),
    sa.Column('is_gluten_free', sa.Boolean(), nullable=False),
    sa.Column('is_lactose_free', sa.Boolean(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('is_halal', sa.Boolean(), nullable=False),
    sa.Column('is_kosher', sa.Boolean(), nullable=False),
    sa.Column('allergens_detected', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('barcode')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.BigInteger(), nullable=False),
    sa.Column('scan_type', sa.Enum('BARCODE', 'OCR_LABEL', 'MANUAL_INPUT', name='scan_type'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_history_scanned_at'), 'scan_history', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_scan_history_user_id'), 'scan_history', ['user_id'], unique=False)
    op.create_table('user_health_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('has_diabetes', sa.Boolean(), nullable=False),
    sa.Column('has_hypertension', sa.Boolean(), nullable=False),
    sa.Column('has_kidney_disease', sa.Boolean(), nullable=False),
    sa.Column('has_gout', sa.Boolean(), nullable=False),
    sa.Column('is_pregnant', sa.Boolean(), nullable=False),
    sa.Column('for_children', sa.Boolean(), nullable=False),
    sa.Column('has_high_cholesterol', sa.Boolean(), nullable=False),
    sa.Column('avoid_gluten', sa.Boolean(), nullable=False),
    sa.Column('avoid_lactose', sa.Boolean(), nullable=False),
    sa.Column('avoid_peanuts', sa.Boolean(), nullable=False),
    sa.Column('avoid_soy', sa.Boolean(), nullable=False),
    sa.Column('avoid_tree_nuts', sa.Boolean(), nullable=False),
    sa.Column('require_vegan', sa.Boolean(), nullable=False),
    sa.Column('require_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('require_halal', sa.Boolean(), nullable=False),
    sa.Column('require_kosher', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_health_profiles')
    op.drop_index(op.f('ix_scan_history_user_id'), table_name='scan_history')
    op.drop_index(op.f('ix_scan_history_scanned_at'), table_name='scan_history')
    op.drop_table('scan_history')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_ingredients_e_number'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_common_name'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
