"""barcode discovery provenance

Revision ID: cf5522508f9a
Revises: 64dfe47cbbf7
Create Date: 2026-08-31 07:42:46.580103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5522508f9a'
down_revision: Union[str, None] = '64dfe47cbbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('external_last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('raw_ingredient_text', sa.Text(), nullable=True),
    sa.Column('normalized_ingredients_json', sa.Text(), nullable=True),
    sa.Column('nutrition_json', sa.Text(), nullable=True),
    sa.Column('allergens', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('raw_metadata_json', sa.Text(), nullable=True),
    sa.Column('is_conflicting', sa.Boolean(), nullable=False),
    sa.Column('used_for_persisted_product', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['barcode'], ['products.barcode'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode', 'provider', name='uq_product_sources_barcode_provider')
    )
    op.create_index(op.f('ix_product_sources_barcode'), 'product_sources', ['barcode'], unique=False)
    op.add_column('products', sa.Column('source', sa.String(length=32), server_default='local', nullable=False))
    op.add_column('products', sa.Column('source_confidence', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('products', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('products', sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'last_verified_at')
    op.drop_column('products', 'discovered_at')
    op.drop_column('products', 'is_verified')
    op.drop_column('products', 'source_confidence')
    op.drop_column('products', 'source')
    op.drop_index(op.f('ix_product_sources_barcode'), table_name='product_sources')
    op.drop_table('product_sources')
    # ### end Alembic commands ###
